version: "3.7"
services:
  frontend:
    build: .
    container_name: react-rolodex
    restart: unless-stopped
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./src/:/app/src
      - ./node_modules:/app/node_modules
    networks:
      - app-network


networks:
  app-network:
    driver: bridge